SSD_LAYOUT_DICT = {
    "code": "smallest_stellated_dodecahedron",
    "logical_qubits": {
        "L1": {"ind": 0, "log_x": [], "log_z": []},
        "L2": {"ind": 1, "log_x": [], "log_z": []},
        "L3": {"ind": 2, "log_x": [], "log_z": []},
        "L4": {"ind": 3, "log_x": [], "log_z": []},
        "L5": {"ind": 4, "log_x": [], "log_z": []},
        "L6": {"ind": 5, "log_x": [], "log_z": []},
        "L7": {"ind": 6, "log_x": [], "log_z": []},
        "L8": {"ind": 7, "log_x": [], "log_z": []},
    },
    "distance": 3,
    "distance_x": 3,
    "distance_z": 3,
    "interaction_order": {str: []},
    "layout": [
        {
            "qubit": "D1",
            "role": "data",
            "stab_type": None,
            "ind": 12,
            "neighbors": {
                "XA": "X2",
                "XB": "X5",
                "ZA": "Z1",
                "ZB": "Z12",
            },
            "coords": [-0.0005, -1.995],
        },
        {
            "qubit": "D2",
            "role": "data",
            "stab_type": None,
            "ind": 13,
            "neighbors": {
                "XA": "X6",
                "XB": "X12",
                "ZA": "Z1",
                "ZB": "Z5",
            },
            "coords": [-1.2035, -1.656],
        },
        {
            "qubit": "D3",
            "role": "data",
            "stab_type": None,
            "ind": 14,
            "neighbors": {
                "XA": "X5",
                "XB": "X7",
                "ZA": "Z1",
                "ZB": "Z6",
            },
            "coords": [-0.4785, -1.2545],
        },
        {
            "qubit": "D4",
            "role": "data",
            "stab_type": None,
            "ind": 15,
            "neighbors": {
                "XA": "X2",
                "XB": "X6",
                "ZA": "Z1",
                "ZB": "Z7",
            },
            "coords": [0.4785, -1.2545],
        },
        {
            "qubit": "D5",
            "role": "data",
            "stab_type": None,
            "ind": 16,
            "neighbors": {
                "XA": "X7",
                "XB": "X12",
                "ZA": "Z1",
                "ZB": "Z2",
            },
            "coords": [1.203, -1.656],
        },
        {
            "qubit": "D6",
            "role": "data",
            "stab_type": None,
            "ind": 17,
            "neighbors": {
                "XA": "X1",
                "XB": "X8",
                "ZA": "Z2",
                "ZB": "Z7",
            },
            "coords": [1.045, -0.843],
        },
        {
            "qubit": "D7",
            "role": "data",
            "stab_type": None,
            "ind": 18,
            "neighbors": {
                "XA": "X3",
                "XB": "X7",
                "ZA": "Z2",
                "ZB": "Z8",
            },
            "coords": [1.3405, 0.067],
        },
        {
            "qubit": "D8",
            "role": "data",
            "stab_type": None,
            "ind": 19,
            "neighbors": {
                "XA": "X8",
                "XB": "X12",
                "ZA": "Z2",
                "ZB": "Z3",
            },
            "coords": [1.9465, 0.6325],
        },
        {
            "qubit": "D9",
            "role": "data",
            "stab_type": None,
            "ind": 20,
            "neighbors": {
                "XA": "X1",
                "XB": "X3",
                "ZA": "Z2",
                "ZB": "Z12",
            },
            "coords": [1.897, -0.6165],
        },
        {
            "qubit": "D10",
            "role": "data",
            "stab_type": None,
            "ind": 21,
            "neighbors": {
                "XA": "X2",
                "XB": "X9",
                "ZA": "Z3",
                "ZB": "Z8",
            },
            "coords": [1.124, 0.734],
        },
        {
            "qubit": "D11",
            "role": "data",
            "stab_type": None,
            "ind": 22,
            "neighbors": {
                "XA": "X4",
                "XB": "X8",
                "ZA": "Z3",
                "ZB": "Z9",
            },
            "coords": [0.35, 1.2965],
        },
        {
            "qubit": "D12",
            "role": "data",
            "stab_type": None,
            "ind": 23,
            "neighbors": {
                "XA": "X9",
                "XB": "X12",
                "ZA": "Z3",
                "ZB": "Z4",
            },
            "coords": [0, 2.047],
        },
        {
            "qubit": "D13",
            "role": "data",
            "stab_type": None,
            "ind": 24,
            "neighbors": {
                "XA": "X2",
                "XB": "X4",
                "ZA": "Z3",
                "ZB": "Z12",
            },
            "coords": [1.1725, 1.614],
        },
        {
            "qubit": "D14",
            "role": "data",
            "stab_type": None,
            "ind": 25,
            "neighbors": {
                "XA": "X3",
                "XB": "X10",
                "ZA": "Z4",
                "ZB": "Z9",
            },
            "coords": [-0.35, 1.2965],
        },
        {
            "qubit": "D15",
            "role": "data",
            "stab_type": None,
            "ind": 26,
            "neighbors": {
                "XA": "X5",
                "XB": "X9",
                "ZA": "Z4",
                "ZB": "Z10",
            },
            "coords": [-1.124, 0.734],
        },
        {
            "qubit": "D16",
            "role": "data",
            "stab_type": None,
            "ind": 27,
            "neighbors": {
                "XA": "X10",
                "XB": "X12",
                "ZA": "Z4",
                "ZB": "Z5",
            },
            "coords": [-1.9465, 0.6325],
        },
        {
            "qubit": "D17",
            "role": "data",
            "stab_type": None,
            "ind": 28,
            "neighbors": {
                "XA": "X3",
                "XB": "X5",
                "ZA": "Z4",
                "ZB": "Z12",
            },
            "coords": [-1.1725, 1.614],
        },
        {
            "qubit": "D18",
            "role": "data",
            "stab_type": None,
            "ind": 29,
            "neighbors": {
                "XA": "X4",
                "XB": "X6",
                "ZA": "Z5",
                "ZB": "Z10",
            },
            "coords": [-1.341, 0.0675],
        },
        {
            "qubit": "D19",
            "role": "data",
            "stab_type": None,
            "ind": 30,
            "neighbors": {
                "XA": "X1",
                "XB": "X10",
                "ZA": "Z5",
                "ZB": "Z6",
            },
            "coords": [-1.0455, -0.8425],
        },
        {
            "qubit": "D20",
            "role": "data",
            "stab_type": None,
            "ind": 31,
            "neighbors": {
                "XA": "X1",
                "XB": "X4",
                "ZA": "Z5",
                "ZB": "Z12",
            },
            "coords": [-1.8975, -0.6165],
        },
        {
            "qubit": "D21",
            "role": "data",
            "stab_type": None,
            "ind": 32,
            "neighbors": {
                "XA": "X1",
                "XB": "X11",
                "ZA": "Z6",
                "ZB": "Z7",
            },
            "coords": [0, -0.853],
        },
        {
            "qubit": "D22",
            "role": "data",
            "stab_type": None,
            "ind": 33,
            "neighbors": {
                "XA": "X2",
                "XB": "X11",
                "ZA": "Z7",
                "ZB": "Z8",
            },
            "coords": [0.811, -0.264],
        },
        {
            "qubit": "D23",
            "role": "data",
            "stab_type": None,
            "ind": 34,
            "neighbors": {
                "XA": "X3",
                "XB": "X11",
                "ZA": "Z8",
                "ZB": "Z9",
            },
            "coords": [0.501, 0.6905],
        },
        {
            "qubit": "D24",
            "role": "data",
            "stab_type": None,
            "ind": 35,
            "neighbors": {
                "XA": "X4",
                "XB": "X11",
                "ZA": "Z9",
                "ZB": "Z10",
            },
            "coords": [-0.501, 0.6905],
        },
        {
            "qubit": "D25",
            "role": "data",
            "stab_type": None,
            "ind": 36,
            "neighbors": {
                "XA": "X5",
                "XB": "X11",
                "ZA": "Z6",
                "ZB": "Z10",
            },
            "coords": [-0.8115, -0.2635],
        },
        {
            "qubit": "D26",
            "role": "data",
            "stab_type": None,
            "ind": 37,
            "neighbors": {
                "XA": "X7",
                "XB": "X10",
                "ZA": "Z6",
                "ZB": "Z11",
            },
            "coords": [-0.2245, -0.3365],
        },
        {
            "qubit": "D27",
            "role": "data",
            "stab_type": None,
            "ind": 38,
            "neighbors": {
                "XA": "X6",
                "XB": "X8",
                "ZA": "Z7",
                "ZB": "Z11",
            },
            "coords": [0.2445, -0.3365],
        },
        {
            "qubit": "D28",
            "role": "data",
            "stab_type": None,
            "ind": 39,
            "neighbors": {
                "XA": "X7",
                "XB": "X9",
                "ZA": "Z8",
                "ZB": "Z11",
            },
            "coords": [0.3955, 0.1285],
        },
        {
            "qubit": "D29",
            "role": "data",
            "stab_type": None,
            "ind": 40,
            "neighbors": {
                "XA": "X8",
                "XB": "X10",
                "ZA": "Z9",
                "ZB": "Z11",
            },
            "coords": [0, 0.416],
        },
        {
            "qubit": "D30",
            "role": "data",
            "stab_type": None,
            "ind": 41,
            "neighbors": {
                "XA": "X6",
                "XB": "X9",
                "ZA": "Z10",
                "ZB": "Z11",
            },
            "coords": [-0.3955, 0.1285],
        },
        {
            "qubit": "X1",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 42,
            "neighbors": {
                "DA": "D6",
                "DB": "D9",
                "DC": "D19",
                "DD": "D20",
                "DE": "D21",
            },
            "coords": [0.025, -1.5382],
        },
        {
            "qubit": "X2",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 43,
            "neighbors": {
                "DA": "D1",
                "DB": "D4",
                "DC": "D10",
                "DD": "D13",
                "DE": "D22",
            },
            "coords": [1.5114, -0.4582],
        },
        {
            "qubit": "X3",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 44,
            "neighbors": {
                "DA": "D7",
                "DB": "D9",
                "DC": "D14",
                "DD": "D17",
                "DE": "D23",
            },
            "coords": [0.9436, 1.2898],
        },
        {
            "qubit": "X4",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 45,
            "neighbors": {
                "DA": "D11",
                "DB": "D13",
                "DC": "D18",
                "DD": "D20",
                "DE": "D24",
            },
            "coords": [-0.8936, 1.2898],
        },
        {
            "qubit": "X5",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 46,
            "neighbors": {
                "DA": "D1",
                "DB": "D3",
                "DC": "D15",
                "DD": "D17",
                "DE": "D25",
            },
            "coords": [-1.4614, -0.4582],
        },
        {
            "qubit": "X6",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 47,
            "neighbors": {
                "DA": "D2",
                "DB": "D4",
                "DC": "D18",
                "DD": "D27",
                "DE": "D30",
            },
            "coords": [-0.491, -0.685],
        },
        {
            "qubit": "X7",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 48,
            "neighbors": {"DA": "D3", "DB": "D5", "DC": "D7", "DD": "D26", "DE": "D28"},
            "coords": [0.541, -0.685],
        },
        {
            "qubit": "X8",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 49,
            "neighbors": {
                "DA": "D6",
                "DB": "D8",
                "DC": "D11",
                "DD": "D27",
                "DE": "D29",
            },
            "coords": [0.8596, 0.2962],
        },
        {
            "qubit": "X9",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 50,
            "neighbors": {
                "DA": "D10",
                "DB": "D12",
                "DC": "D15",
                "DD": "D28",
                "DE": "D30",
            },
            "coords": [0.025, 0.903],
        },
        {
            "qubit": "X10",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 51,
            "neighbors": {
                "DA": "D14",
                "DB": "D16",
                "DC": "D19",
                "DD": "D26",
                "DE": "D29",
            },
            "coords": [-0.8096, 0.2962],
        },
        {
            "qubit": "X11",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 52,
            "neighbors": {
                "DA": "D21",
                "DB": "D22",
                "DC": "D23",
                "DD": "D24",
                "DE": "D25",
            },
            "coords": [0.025, 0.025],
        },
        {
            "qubit": "X12",
            "role": "anc",
            "stab_type": "x_type",
            "ind": 53,
            "neighbors": {"DA": "D2", "DB": "D5", "DC": "D8", "DD": "D12", "DE": "D16"},
            "coords": [2.025, -1.975],
        },
        {
            "qubit": "Z1",
            "role": "anc",
            "stab_type": "z_type",
            "ind": -1,
            "neighbors": {"DA": "D1", "DB": "D2", "DC": "D3", "DD": "D4", "DE": "D5"},
            "coords": [-0.025, -1.5882],
        },
        {
            "qubit": "Z2",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 0,
            "neighbors": {"DA": "D5", "DB": "D6", "DC": "D7", "DD": "D8", "DE": "D9"},
            "coords": [1.4614, -0.5082],
        },
        {
            "qubit": "Z3",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 1,
            "neighbors": {
                "DA": "D8",
                "DB": "D10",
                "DC": "D11",
                "DD": "D12",
                "DE": "D13",
            },
            "coords": [0.8936, 1.2398],
        },
        {
            "qubit": "Z4",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 2,
            "neighbors": {
                "DA": "D12",
                "DB": "D14",
                "DC": "D15",
                "DD": "D16",
                "DE": "D17",
            },
            "coords": [-0.9436, 1.2398],
        },
        {
            "qubit": "Z5",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 3,
            "neighbors": {
                "DA": "D2",
                "DB": "D16",
                "DC": "D18",
                "DD": "D19",
                "DE": "D20",
            },
            "coords": [-1.5114, -0.5082],
        },
        {
            "qubit": "Z6",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 4,
            "neighbors": {
                "DA": "D3",
                "DB": "D19",
                "DC": "D21",
                "DD": "D25",
                "DE": "D26",
            },
            "coords": [-0.541, -0.735],
        },
        {
            "qubit": "Z7",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 5,
            "neighbors": {
                "DA": "D4",
                "DB": "D6",
                "DC": "D21",
                "DD": "D22",
                "DE": "D27",
            },
            "coords": [0.491, -0.735],
        },
        {
            "qubit": "Z8",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 6,
            "neighbors": {
                "DA": "D7",
                "DB": "D10",
                "DC": "D22",
                "DD": "D23",
                "DE": "D28",
            },
            "coords": [0.8096, 0.2462],
        },
        {
            "qubit": "Z9",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 7,
            "neighbors": {
                "DA": "D11",
                "DB": "D14",
                "DC": "D23",
                "DD": "D24",
                "DE": "D29",
            },
            "coords": [-0.025, 0.853],
        },
        {
            "qubit": "Z10",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 8,
            "neighbors": {
                "DA": "D15",
                "DB": "D18",
                "DC": "D24",
                "DD": "D25",
                "DE": "D30",
            },
            "coords": [-0.8596, 0.2462],
        },
        {
            "qubit": "Z11",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 9,
            "neighbors": {
                "DA": "D26",
                "DB": "D27",
                "DC": "D28",
                "DD": "D29",
                "DE": "D30",
            },
            "coords": [-0.025, -0.025],
        },
        {
            "qubit": "Z12",
            "role": "anc",
            "stab_type": "z_type",
            "ind": 10,
            "neighbors": {
                "DA": "D1",
                "DB": "D9",
                "DC": "D13",
                "DD": "D17",
                "DE": "D20",
            },
            "coords": [1.975, -2.025],
        },
    ],
}


INTERACTION_ORDER = {
    "X1": [],
    "X2": [],
}
